repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.1
    hooks:
      - id: flake8
        additional_dependencies: ["flake8-import-order"]
      - id: flake8
        name: flake8-pyx
        language: python_venv
        files: \.(pyx|pxd)$
        types:
          - file
        args:  [--append-config=.flake8-pyx]
