name: release-dev

on: 
  push:
    branches: [feature/publish-pypi]

jobs:
  release-windows:
    name: Build and publish windows wheel to TestPyPI
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install pep517
      run: >-
        python -m
        pip install
        pep517
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        pep517.build
        --source
        --binary
        --out-dir dist/
        .
    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/