name: release-dev

on: 
  push:
    branches: [feature/publish-pypi]

jobs:
  build-windows:
    name: Build Windows wheel
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install pep517
      run: >-
        python -m
        pip install
        pep517
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        pep517.build
        --source
        --binary
        --out-dir dist/
        .
    - uses: actions/upload-artifact@v2
      with:
        name: windows-wheel
        path: dist/*

  build-linux:
    name: Build linux wheel
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2
    - name: Build linux wheels
      uses: RalfG/python-wheels-manylinux-build@v0.2.2-manylinux2010_x86_64
      with:
        python-versions: 'cp36-cp36m cp37-cp37m cp38-cp38'
        build-requirements: 'cython numpy'
    - uses: actions/upload-artifact@v2
      with:
        name: linux-wheel
        path: wheelhouse/*
  
  publish:
    name: Publish to Test PyPI
    runs-on: ubuntu-latest
    needs: ['build-windows', 'build-linux']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        path: dist
    - name: Move to dist/
      run: |
        cp -v dist/**/* dist/ &&
        rm -rf dist/*/
    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/
    
